- name: checkout source code
  git:
    repo=https://review.openstack.org/openstack/{{ item.repo }}.git
    dest=/opt/{{ item.repo }}
    force=yes
    refspec={{ item.version }}
  with_items:
    - { repo: 'keystonemiddleware', version: "{{ keystonemiddleware_version | default('refs/heads/master') }}" }
    - { repo: 'python-keystoneclient', version: "{{ keystoneclient_version | default('refs/heads/master') }}" }

- name: create dirs for wsgi scripts
  file:
    path=/var/{{ item }}
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - echo

- name: deploy an echo wsgi script
  template:
    src=echo.py
    dest=/var/echo/echo.py
    owner=www-data
    group=www-data
    mode=0400
  tags:
    - config

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pycrypto
    - python-memcached
    - six  # workaround for debian wheezy?

- name: install python projects
  shell: cd /opt/{{ item }} && python setup.py install
  with_items:
    - python-keystoneclient
    - keystonemiddleware

- name: test if apache is installed
  command: which apache2
  register: apache_installed
  tags:
    - config

- name: configure apache
  include: apache.yaml
  when: apache_installed
  tags:
    - config
