- name: checkout source code
  git:
    repo=https://review.openstack.org/openstack/{{ item.repo }}.git
    dest=/opt/{{ item.repo }}
    force=yes
    refspec={{ item.version }}
  with_items:
    - { repo: 'keystonemiddleware', version: "{{ keystonemiddleware_version | default('refs/heads/master') }}" }
    - { repo: 'python-keystoneclient', version: "{{ keystoneclient_version | default('refs/heads/master') }}" }
  notify: restart services

- name: deploy a virtual hosts
  template:
    src={{ item }}.vhost
    dest=/etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - echo
  notify: restart services
  tags:
    - config

- name: create dirs for wsgi scripts
  file:
    path=/var/{{ item }}
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - echo
  notify: restart services

- name: deploy an echo wsgi script
  template:
    src=echo.py
    dest=/var/echo/echo.py
    owner=www-data
    group=www-data
    mode=0400
  notify: restart services
  tags:
    - config

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pycrypto
    - python-memcached
    - six  # workaround for debian wheezy?
  notify: restart services

- name: install python projects
  shell: cd /opt/{{ item }} && python setup.py install
  with_items:
    - python-keystoneclient
    - keystonemiddleware
  notify: restart services
