language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - ansible-playbook --connection=local --inventory-file='localhost,' --sudo deploy.yaml
script: OS_AUTH_URL='http://localhost:35357/v3' python -m unittest discover
