language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - ansible-galaxy install --roles-path=playbooks/roles/ --role-file=ansible-requirements.txt
  - ansible-playbook --connection=local --inventory-file='localhost,' --sudo deploy.yaml
script: HOST='localhost' python -m unittest discover
