- hosts: db
  gather_facts: false
  tasks:
  - name: stop mysql
    service:
      name=mysql
      state=stopped

  - name: stop rsync
    service:
      name=rsync
      state=stopped

  - name: kill the cluster
    shell: pkill -9 -f {{ item }}
    with_items:
    - maria
    - mysql
    - rsync
    ignore_errors: true

- hosts: db[0]
  gather_facts: false
  tasks:
  - name: fetch debian maintenance configuration
    fetch:
      src=/etc/mysql/debian.cnf
      dest=/tmp/

  - name: start the first node
    service:
      name=mysql
      state=started
      arguments=--wsrep-new-cluster

- hosts: db
  tasks:
  - name: distribute debian maintenance configuration
    copy:
      src=/tmp/{{ groups['db'][0] }}/etc/mysql/debian.cnf
      dest=/etc/mysql/debian.cnf

- hosts: db
  gather_facts: false
  tasks:
  - name: start secondary nodes
    service:
      name=mysql
      state=started
    environment:
      MYSQLD_STARTUP_TIMEOUT: 300

  - name: check cluster size
    shell: >
      mysql -e "SHOW STATUS LIKE 'wsrep_cluster_size';" | awk '{ print $2 }' | awk 'FNR == 2 { print }'
    register: cluster_size
  - name: cluster size
    debug: msg='{{ cluster_size.stdout }}'
