- hosts: db
  gather_facts: false
  tasks:
  - name: stop mysql
    service:
      name=mysql
      state=stopped

- hosts: db[0]
  gather_facts: false
  tasks:
  - name: fetch debian maintenance configuration
    fetch:
      src=/etc/mysql/debian.cnf
      dest=/tmp/

  - name: start the first node
    service:
      name=mysql
      state=started
      arguments=--wsrep-new-cluster

- hosts: secondary_db
  gather_facts: false
  tasks:
  - name: distribute debian maintenance configuration
    copy:
      src=/tmp/{{ primary_db_hostname }}/etc/mysql/debian.cnf
      dest=/etc/mysql/debian.cnf

- hosts: secondary_db
  gather_facts: false
  serial: 1
  tasks:
  - name: start secondary nodes
    service:
      name=mysql
      state=started
      arguments=--wsrep_sst_donor={{ primary_db_hostname }}

- hosts: db
  gather_facts: false
  tasks:
  - name: check cluster size
    shell: >
      mysql -e "SHOW STATUS LIKE 'wsrep_cluster_size';" | awk '{ print $2 }' | awk 'FNR == 2 { print }'
    register: cluster_size
  - name: cluster size
    debug: msg='{{ cluster_size.stdout }}'
