- name: wipe message of the day
  template:
    src=message-of-the-day
    dest=/etc/motd

- name: install global inputrc
  template:
    src=inputrc
    dest=/etc/inputrc

- name: install unattended upgrades
  apt:
    pkg=unattended-upgrades
    state=present
    update_cache=yes

- name: configure auto upgrades
  template:
    src=auto-upgrades
    dest=/etc/apt/apt.conf.d/20auto-upgrades
    mode=0644

- name: configure unattended upgrades
  template:
    src=unattended-upgrades
    dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: install apt packages
  apt:
    pkg={{ item }}
  with_items:
    - git
    - apache2
    - libapache2-mod-wsgi

- name: checkout the master branch of keystone
  git:
    repo=https://github.com/openstack/keystone.git
    dest=/opt/keystone
    force=yes
