- name: install apt packages
  apt:
    pkg={{ item }}
  with_items:
    - git
    - apache2
    - libapache2-mod-wsgi
    - python-dev
    - python-pip
    - libxml2-dev  # only required for XML support
    - libxslt1-dev  # only required for XML support
  notify: restart apache2

- name: checkout the master branch of keystone
  git:
    repo=https://github.com/openstack/keystone.git
    dest=/opt/keystone
    force=yes
  notify: restart apache2

- name: remove the default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default
    state=absent
  notify: restart apache2

- name: deploy a keystone virtual host
  template:
    src=keystone.vhost
    dest=/etc/apache2/sites-enabled/keystone
  notify: restart apache2

- name: deploy an echo virtual host
  template:
    src=echo.vhost
    dest=/etc/apache2/sites-enabled/echo
  notify: restart apache2

- name: establish a configuration directory for keystone
  file:
    path=/etc/keystone
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  notify: restart apache2

- name: create a dir for keystone wsgi scripts
  file:
    path=/var/keystone
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  notify: restart apache2

- name: create a dir for echo wsgi scripts
  file:
    path=/var/echo
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  notify: restart apache2

- name: deploy a keystone wsgi script
  template:
    src=keystone.wsgi
    dest=/var/keystone/keystone.wsgi
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache2

- name: deploy an echo wsgi script
  template:
    src=echo.py
    dest=/var/echo/echo.py
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache2

- name: deploy keystone.conf
  template:
    src=keystone.conf
    dest=/etc/keystone/keystone.conf
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache2

- name: deploy pipeline configuration
  template:
    src=paste.ini
    dest=/etc/keystone/paste.ini
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache2

- name: deploy policy.json
  template:
    src=policy.json
    dest=/etc/keystone/policy.json
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache2

- name: deploy public CA certificate
  template:
    src=ca.pem
    dest=/etc/keystone/ca.pem
    owner=www-data
    group=www-data
    mode=0400

- name: deploy private CA certificate
  template:
    src=ca_key.pem
    dest=/etc/keystone/ca_key.pem
    owner=www-data
    group=www-data
    mode=0400

- name: deploy public signing certificate
  template:
    src=signing.pem
    dest=/etc/keystone/signing.pem
    owner=www-data
    group=www-data
    mode=0400

- name: deploy private signing key
  template:
    src=signing_key.pem
    dest=/etc/keystone/signing_key.pem
    owner=www-data
    group=www-data
    mode=0400

- name: install keystone
  shell: cd /opt/keystone && python setup.py install
  notify: restart apache2

- name: install the latest versions of any python requirements
  pip:
    requirements=/opt/keystone/requirements.txt
    state=latest
  notify: restart apache2

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
  - python-memcached
  notify: restart apache2

- name: run database migrations
  shell: keystone-manage db_sync
