- name: update apt cache
  apt:
    update_cache=yes

- name: install apt packages
  apt:
    pkg={{ item }}
  with_items:
    - git
    - apache2
    - libapache2-mod-wsgi
    - python-dev
    - libffi-dev
  notify: restart services

- name: checkout source code
  git:
    repo=https://github.com/openstack/{{ item.repo }}.git
    dest=/opt/{{ item.repo }}
    force=yes
    version={{ item.version }}
  with_items:
    - { repo: 'keystone', version: "{{ keystone_version | default('master') }}"  }
    - { repo: 'keystonemiddleware', version: "{{ keystonemiddleware_version | default('master') }}" }
    - { repo: 'python-keystoneclient', version: "{{ keystoneclient_version | default('master') }}" }
  notify: restart services

- name: remove the default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default
    state=absent
  notify: restart services

- name: deploy a virtual hosts
  template:
    src={{ item }}.vhost
    dest=/etc/apache2/sites-enabled/{{ item }}
  with_items:
    - keystone
    - echo
  notify: restart services

- name: establish a configuration directory for keystone
  file:
    path=/etc/keystone
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  notify: restart services

- name: create dirs for wsgi scripts
  file:
    path=/var/{{ item }}
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - keystone
    - echo
  notify: restart services

- name: deploy keystone wsgi scripts
  template:
    src=keystone.wsgi
    dest=/var/keystone/{{ item }}
    owner=www-data
    group=www-data
    mode=0400
  notify: restart services
  with_items:
    - main
    - admin

- name: deploy an echo wsgi script
  template:
    src=echo.py
    dest=/var/echo/echo.py
    owner=www-data
    group=www-data
    mode=0400
  notify: restart services

- name: deploy keystone configuration files
  template:
    src={{ item }}
    dest=/etc/keystone/{{ item }}
    owner=www-data
    group=www-data
    mode=0400
  with_items:
    - keystone.conf
    - paste.ini
    - policy.json
  notify: restart services

# this is a workaround for installing on Debian Wheezy
- name: install python-six
  pip:
    name=six
    state=latest

- name: install python projects
  shell: cd /opt/{{ item }} && python setup.py install
  with_items:
    - keystone
    - keystonemiddleware
    - python-keystoneclient
  notify: restart services

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
    - python-memcached
    - pycrypto
  notify: restart services

- name: run database migrations
  shell: keystone-manage db_sync
