- name: update apt cache
  apt:
    update_cache=yes

- name: install apt packages
  apt:
    pkg={{ item }}
  with_items:
    - git
    - libffi-dev
    - python-dev
    - supervisor
  notify: restart services

- name: checkout source code
  git:
    repo=https://github.com/openstack/{{ item.repo }}.git
    dest=/opt/{{ item.repo }}
    force=yes
    version={{ item.version }}
  with_items:
    - { repo: 'keystone', version: "{{ keystone_version | default('master') }}"  }
    - { repo: 'keystonemiddleware', version: "{{ keystonemiddleware_version | default('master') }}" }
    - { repo: 'python-keystoneclient', version: "{{ keystoneclient_version | default('master') }}" }
  notify: restart services

- name: create application users
  user:
    name={{ item }}
    createhome=yes
  with_items:
    - echo
    - keystone
  notify: restart services

- name: establish a configuration directory for keystone
  file:
    path=/etc/keystone
    state=directory
    owner=keystone
    group=keystone
    mode=0755
  notify: restart services

- name: create dirs for wsgi scripts
  file:
    path=/var/{{ item }}
    state=directory
    owner={{ item }}
    group={{ item }}
    mode=0755
  with_items:
    - echo
    - keystone
  notify: restart services

- name: deploy an echo wsgi script
  template:
    src=echo.py
    dest=/var/echo/echo.py
    owner=echo
    group=echo
    mode=0400
  notify: restart services

- name: deploy keystone configuration files
  template:
    src={{ item }}
    dest=/etc/keystone/{{ item }}
    owner=keystone
    group=keystone
    mode=0400
  with_items:
    - keystone.conf
    - paste.ini
    - policy.json
  notify: restart services

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pycrypto
    - python-memcached
    - six  # workaround for debian wheezy?
  notify: restart services

- name: install python projects
  shell: cd /opt/{{ item }} && python setup.py install
  with_items:
    - keystone
    - keystonemiddleware
    - python-keystoneclient
  notify: restart services

- name: run database migrations
  shell: keystone-manage db_sync

- name: deploy supervisor configs
  template:
    src=supervisor.{{ item }}.conf
    dest=/etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - keystone
    - echo

- name: ensure supervised processes are present
  shell: /usr/bin/supervisorctl reread && /usr/bin/supervisorctl update
