- name: install apt packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=600
  with_items:
    - apache2
    - libapache2-mod-wsgi
  notify: restart services

- name: remove the default virtual host
  file:
    path={{ item }}
    state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default
    - /etc/apache2/sites-enabled/000-default.conf
  notify: restart services
  tags:
  - config
