- name: install apt packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=600
  with_items:
    - apache2
    - apache2-mpm-prefork
    - libapache2-mod-wsgi
  notify: restart services

- name: disable mpm_event
  command: a2dismod mpm_event
  ignore_errors: true

- name: disable mpm_worker
  command: a2dismod mpm_worker
  ignore_errors: true

- name: enable mpm_prefork
  command: a2enmod mpm_prefork
  ignore_errors: true

- name: remove the default virtual host
  file:
    path={{ item }}
    state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default
    - /etc/apache2/sites-enabled/000-default.conf
  notify: restart services
  tags:
  - config
