- name: install apt packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=600
  with_items:
    - apache2
    - apache2-mpm-prefork
    - libapache2-mod-wsgi
  notify: restart services

- name: check if mpm_event is enabled
  stat: path=/etc/apache2/mods-enabled/mpm_event.load
  register: mpm_event

- name: disable mpm_event
  command: a2dismod mpm_event
  when: mpm_event.stat.exists

- name: check if mpm_worker is enabled
  stat: path=/etc/apache2/mods-enabled/mpm_worker.load
  register: mpm_worker

- name: disable mpm_worker
  command: a2dismod mpm_worker
  when: mpm_worker.stat.exists

- name: check if mpm_prefork is enabled
  stat: path=/etc/apache2/mods-enabled/mpm_prefork.load
  register: mpm_prefork

- name: enable mpm_prefork
  command: a2enmod mpm_prefork
  when: not mpm_prefork.stat.exists

- name: remove the default virtual host
  file:
    path={{ item }}
    state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default
    - /etc/apache2/sites-enabled/000-default.conf
  notify: restart services
  tags:
  - config
