- name: install apt packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=600
  with_items:
    - git
    - libffi-dev
    - python-dev
  notify: restart services

- name: detect apache version
  shell: "apache2 -v | grep 'Apache/2.4'"
  register: apache24
  ignore_errors: True
  tags:
    - config

- name: checkout source code
  git:
    repo=https://review.openstack.org/openstack/{{ item.repo }}.git
    dest=/opt/{{ item.repo }}
    force=yes
    refspec={{ item.version }}
  with_items:
    - { repo: 'keystone', version: "{{ keystone_version | default('refs/heads/master') }}"  }
    - { repo: 'python-keystoneclient', version: "{{ keystoneclient_version | default('refs/heads/master') }}" }
  notify: restart services

- name: deploy a virtual hosts
  template:
    src={{ item }}.vhost
    dest=/etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - keystone
  notify: restart services

- name: establish a configuration directory for keystone
  file:
    path=/etc/keystone
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  notify: restart services

- name: create dirs for wsgi scripts
  file:
    path=/var/{{ item }}
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - keystone
  notify: restart services

- name: deploy keystone wsgi scripts
  template:
    src=keystone.wsgi
    dest=/var/keystone/{{ item }}
    owner=www-data
    group=www-data
    mode=0400
  notify: restart services
  with_items:
    - admin
    - main

- name: deploy keystone configuration files
  template:
    src={{ item }}
    dest=/etc/keystone/{{ item }}
    owner=www-data
    group=www-data
    mode=0400
  with_items:
    - keystone.conf
    - paste.ini
    - policy.json
  notify: restart services

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pycrypto
    - python-memcached
    - six  # workaround for debian wheezy?
  notify: restart services

- name: install python projects
  shell: cd /opt/{{ item }} && python setup.py install
  with_items:
    - keystone
    - python-keystoneclient
  notify: restart services

- name: run database migrations
  shell: keystone-manage db_sync
