- name: install apt packages
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=600
  with_items:
    - mysql-server
    - python-mysqldb

- name: create a database for keystone
  mysql_db: name=keystone state=present

- name: create insecure keystone user
  mysql_user:
    name=keystone
    host=localhost
    password=keystone
    priv=keystone.*:ALL
